# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish AuthServer
      run: |
        cd src/Marci.PathPlanningSystem.AuthServer
        dotnet publish -c:Release -o:"../../build/AuthServer" -f:net8.0
    - name: Publish HttpHost
      run: |
        cd..
        cd Marci.PathPlanningSystem.HttpApi.Host
        dotnet publish -c:Release -o:"../../build/HttpHost" -f:net8.0
      
    
